### ISSUE TITLE
QUICKSTART.md problem

### ISSUE THREAD

**Issue by StevenSG03** [GillesVanDeVyver/GCN_multistructure#1]
To follow the QUICKSTART.md to start the model. Do I have to change CONST.py to define the correct path? Since I met an error "assert os.path.exists(dataset_config["img_folder"]), "image repository does not exist." when compiling.

**Comment by gillesvntnu** [comment]
You are correct.
I added the default CONST.py now that should work with the defaults when following QUICKSTART.md.

Thank you for pointing this out.
________________________________
From: Jianxu ***@***.***>
Sent: 07 November 2023 08:29
To: gillesvntnu/GCN_multistructure ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gillesvntnu/GCN_multistructure] QUICKSTART.md problem (Issue #1)


To follow the QUICKSTART.md to start the model. Do I have to change CONST.py to define the correct path? Since I met an error "assert os.path.exists(dataset_config["img_folder"]), "image repository does not exist." when compiling.
